### ISSUE TITLE
Add Websafe font links to lesson 2

### ISSUE THREAD

**Issue by allejo** [YouthTechProgram/Presentations#1]
http://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by thekaveman** [comment]
Part personal opinion, part general internet knowledge:

Don't ever use w3schools as a resource. They aren't legitimately related to the W3C (World Wide Web Consortium), often their information is misleading, and sometimes it is just plain wrong.

**Comment by allejo** [comment]
Good call, I'll add the following link instead?

http://www.w3.org/Style/Examples/007/fonts.en.html

_As a side note to myself, add the prototype_

https://github.com/CityofSantaMonica/YouthTechPrototype
